// <auto-generated />
namespace TechtonicFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class OrderEntityAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderEntityAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202506191820160_OrderEntityAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
